// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.Generated2013.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc2811.Generated2013.Robot;

/**
 *
 */
public class  AutonomousCommand extends Command {
//    DriveInASquare ds;
    boolean Shoot;
    boolean left;
    boolean right;
    boolean front;

    public AutonomousCommand() {
        // Use requires() here to declare subsystem dependencies

        
        
        
    }

    // Called just before this Command runs the first time
    protected void initialize() {
//        ds = new DriveInASquare();
        
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    //    System.out.println("chooser says: Shoot:"+ Shoot + " Left:"+ left + " Right:"+ right+ " Front:"+front);
        
        
        
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
