// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2811.Generated2013;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import org.usfirst.frc2811.Generated2013.commands.autoClimb;
import org.usfirst.frc2811.Generated2013.commands.flip;
import org.usfirst.frc2811.Generated2013.commands.reverse;
import org.usfirst.frc2811.Generated2013.commands.shoot;
import org.usfirst.frc2811.Generated2013.commands.slamreverse;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick joystick;
    public Joystick controller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private JoystickButton trigger;
    private JoystickButton tophat;
    private JoystickButton puase;
    public static JoystickButton FIREINDAHOLE;
    public static JoystickButton collect;
    public static JoystickButton safety;
    public static JoystickButton tigger;
    public static JoystickButton trobutt;
    public static JoystickButton towbutt;
    public static JoystickButton btntomin;
    public static JoystickButton btntomax;
    public static JoystickButton upbtn;
    public static JoystickButton dnbtn;
    public static JoystickButton gears;
    public static JoystickButton creeper;
    public static JoystickButton flip;
    
    public static boolean Paused = true;
    
    public OI() {
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // SmartDashboard Buttons
//        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
//        SmartDashboard.putData("Teleop Command", new TeleopCommand());
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        joystick = new Joystick(1);
        controller = new Joystick(2);
//        trigger = new JoystickButton(joystick, 5);
        
        //trigger.whenPressed(new gearchange(false));
       // trigger.whenPressed(new DriveInASquare());
        
////        tophat = new JoystickButton(joystick, 3);
////        tophat.whenPressed(new ClimbTower());
        
      //  puase = new JoystickButton(joystick,4);
      //  puase.whenPressed(new togglePause());
        
        
        FIREINDAHOLE = new JoystickButton(joystick, 1);
        FIREINDAHOLE.whenPressed(new shoot());
        collect = new JoystickButton(joystick,2);
        collect.whenPressed(new slamreverse());
        btntomin = new JoystickButton(joystick, 12);
        btntomin.whenPressed(new autoClimb());
        creeper = new JoystickButton(joystick, 6);
        flip = new JoystickButton(joystick,7);
        flip.whenPressed(new flip());
//        btntomax = new JoystickButton(joystick, 10);
//        btntomax.whenPressed(new UpToMax());
//        upbtn = new JoystickButton(joystick, 9);
//        upbtn.whenPressed(new Up());
//        dnbtn = new JoystickButton(joystick, 11);
//        dnbtn.whenPressed(new Down());
//        gears = new JoystickButton(joystick,7);
//        gears.whenPressed(new gearchange(false));
//        safety = new JoystickButton(joystick,6);
        
//        trobutt = new JoystickButton(joystick, 3);
//        trobutt.whenPressed(new Down());
//        towbutt = new JoystickButton(joystick, 4);
//        towbutt.whenPressed(new Up());
        
        //tigger = new JoystickButton(joystick,3);
        //tigger.whenPressed(new Travel());
        
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick;
    }

    public Joystick getJoystick2() {
        return controller;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

